services:
  web:
    build: .
    ports: 
      - '8081:80'
    volumes:
      - ./app:/var/www/html/
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      